- id: '1754072831187'
  alias: Speedtest
  description: ''
  triggers:
  - type: data_rate
    device_id: 59278d502c528caf90958b7e55fe58bd
    entity_id: bd15fd98500a1cf5edc7e3131d6639c3
    domain: sensor
    trigger: device
    below: 200
    for:
      hours: 4
      minutes: 0
      seconds: 0
  conditions: []
  actions:
  - action: notify.send_message
    metadata: {}
    data:
      message: Low speed
      title: Speedtest
    target:
      entity_id: notify.portfolio
  mode: single
