---
services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:2025.11.2
    environment:
      TZ: Europe/Stockholm
    network_mode: host
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./config:/config
    devices:
      - /dev/ttyUSB0
    privileged: true
    restart: unless-stopped
